### ISSUE TITLE
create_if_not_exists creates new file name with quotes

### ISSUE THREAD

**Issue by lahmatiy** [titoBouzout/Open-Include#60]
When I trying create new file using Open-Include it creates new filename with quotes in the begining and ending of path. For example:
```
  require('./some/filename.js');
```
will create folder `'` than folder `some` and file with name `filename.js'`.
It worked fine before last package update.
Please, fix it as it's very useful feature for me.
Thanks.

**Comment by titoBouzout** [comment]
I think is done, please let me know

**Comment by lahmatiy** [comment]
Yes, it's fine now.
Thank you.
