### ISSUE TITLE
Wrongly file path resolving with `auto_extension` settings

### ISSUE THREAD

**Issue by lahmatiy** [titoBouzout/Open-Include#61]
For example, project structure:
```
folder1
  index.js
folder2
  foo.js
  test.js
```
Content of `folder2/test.js`
```js
require('./foo.js');
```
With default `auto_extension` settings, if we press `alt+D` inside `'./foo.js'` string Open-Include opens `folder1/index.js` instead of `folder2/foo.js`.
If we override plugin settings:
```json
{
  "auto_extension": []
}
```
than everything works as expected.

**Comment by titoBouzout** [comment]
It works here..

**Comment by lahmatiy** [comment]
Sublime Text 3, Build 3065
No user settings (empty file).
Reproducing on mac and win.

Now I tried remove package from Sublime. `alt+d` does nothing.
Install it back. In new window, project has single folder:
```
t1
  baz.js
  bar.js
  index.js
```
- Open `bar.js`.
- Press `alt+d` with caret inside `'./baz.js'`. Two files opening `baz.js` and `index.js`, and focus on `index.js`.
- Open user preferences for `Open-Include`, add `{ "auto_extension": [] }` and save. Everything works fine.

Sometimes it works ok w/o settings change. But if keep tab with `bar.js` opened and restart Sublime, it starts open two files.

**Comment by titoBouzout** [comment]
Thanks for the detailed explanation, I updated it, please take a look now and let me know.

**Comment by lahmatiy** [comment]
Confirm, works fine.
Thank you!
