### ISSUE TITLE
Line 313

### ISSUE THREAD

**Issue by xHN35RQ** [titoBouzout/Open-Include#68]
Should not [Line 313](https://github.com/titoBouzout/Open-Include/blob/555daefa/open_include.py#L313) be something like the following?

`paths = re.sub('"|\'|<|>|\(|\)|\{|\}\[|\]', '', paths)`

I wonder if I missed this line when I submitted #65

**Comment by titoBouzout** [comment]
can you please explain the reasons behind your reasoning, what changes?
thanks

**Comment by xHN35RQ** [comment]
Well currently it has:

`re.sub('"|\'|<|>|\(|\)|\{|\}', '', paths)`

I just assumed it should be the same as [Line 150](https://github.com/titoBouzout/Open-Include/blob/555daefa/open_include.py#L150) which has:

`re.sub('"|\'|<|>|\(|\)|\{|\}|\[|\]|;', '', file_to_open)`

**Comment by titoBouzout** [comment]
There was a regression in that expression, because we were unable to open file like this "Default (Windows).sublime-keymap" Now fixed and expression updated to match the other one (As appending)

**Comment by xHN35RQ** [comment]
Thanks!
