### ISSUE TITLE
create_if_not_exists still supported?

### ISSUE THREAD

**Issue by xHN35RQ** [titoBouzout/Open-Include#69]
I found `create_if_not_exists` in the settings and tried enabling it in Build 3083 but it seems to do nothing. Is this still supported?

**Comment by titoBouzout** [comment]
Yes, if you have some problem follow the exact instructions noted on readme to report it, thanks

**Comment by xHN35RQ** [comment]
OK will do.

**Comment by titoBouzout** [comment]
create if not exists work only in scope ""parameter.url, string.quoted""

**Comment by xHN35RQ** [comment]
So I guess that means I can't create a new `.md` file from within another `.md` file?

**Comment by titoBouzout** [comment]
Problem with that is that this package will try to get the path of a file, if you turn on create if not exists, depending of the condition, may a very crazy path is created.

**Comment by xHN35RQ** [comment]
Ok np, I'll use another method to create the files. Thanks!
