### ISSUE TITLE
I realised I authored this script!

### ISSUE THREAD

**Issue by jbrooksuk** [titoBouzout/Open-Include#70]
Heh, I thought I wrote the original version of this and [I did](https://github.com/titoBouzout/Open-Include/commit/1284604b80da0e8175cb05ccb424e32fcf8084e2) - that's an old email I used to have.

:smile: 

It's almost the 4th year of this script!

**Comment by titoBouzout** [comment]
Yes, it's noted in the license :) What's your point :P

**Comment by jbrooksuk** [comment]
None :) I just realised and was excited by the four years! Sorry!

**Comment by titoBouzout** [comment]
Ohh well, happy birthday 🎂 ^^

**Comment by FichteFoll** [comment]
It's also the reason why I was added to the SublimeText organisation ([here](https://github.com/titoBouzout/Open-Include/commit/3f794fdb1d34a461244011920dc3adb5b5198098#commitcomment-2103181)). It actually makes me feel old.

**Comment by titoBouzout** [comment]
Four years just a baby =P  Do you wanna transfer the repository somewhere else? where's the cake LOL ~.--

**Comment by jbrooksuk** [comment]
@titoBouzout nope, I don't want to transfer it, honestly. I'm just amazed it's still around haha.

**Comment by titoBouzout** [comment]
I dreamed about hacking the Dreamweaver ALT+D feature .. you just made my dream come true :P

**Comment by jbrooksuk** [comment]
:blush:
